"""Standalone pre-build versioning step — THBR (native idf.py build).

Snapshots working tree to local git, increments build_number.txt, regenerates
main/version.h.

Run BEFORE `idf.py build` (see scripts/build.sh) so version.h is fresh when the
compiler reads it.  Originally a PlatformIO extra_script; ported to a standalone
script when THBR moved to native idf.py — PlatformIO's SCons builder mangles
OpenThread's OPENTHREAD_BUILD_DATETIME string define, so the project builds with
idf.py (CMake+Ninja) instead.

The generated files (build_number.txt, main/version.h) live on the NFS mount
/Public and are read by the compiler right after this script writes them.  A
plain open(...,"w") on NFS only flushes to the client cache — the reader can see
a NUL-prefixed first block (silent corruption).  Hence both are written
atomically + fsync via _atomic_write.  Observed concretely on 2026-05-28:
version.h came back as NUL bytes → "null character(s) ignored [-Werror]" +
FW_VERSION_STRING undeclared.
"""

import datetime
import os
import subprocess


def _atomic_write(path, text):
    """Atomic + fsync write — mandatory for NFS-backed build artefacts.

    os.replace gives a fresh inode so a read-back bypasses the stale page
    cache.  Matters when the tree lives on a network filesystem, where a lazy
    write-back can otherwise hand a second process a half-written file.
    """
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)
    dfd = os.open(os.path.dirname(path) or ".", os.O_RDONLY)
    try:
        os.fsync(dfd)          # dir-fsync commits the rename
    finally:
        os.close(dfd)

PROJECT_DIR  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VERSION_FILE = os.path.join(PROJECT_DIR, "version.txt")
BUILD_FILE   = os.path.join(PROJECT_DIR, "build_number.txt")
HEADER_FILE  = os.path.join(PROJECT_DIR, "main", "version.h")


def _read_version():
    with open(VERSION_FILE) as f:
        v = f.read().strip()
    parts = v.split(".")
    if len(parts) != 2:
        raise RuntimeError(f"version.txt must contain MAJOR.MINOR — got {v!r}")
    return int(parts[0]), int(parts[1])


def _read_build():
    if not os.path.exists(BUILD_FILE):
        return 0
    with open(BUILD_FILE) as f:
        return int((f.read().strip() or "0"))


def _write_build(n):
    _atomic_write(BUILD_FILE, f"{n}\n")


def _is_git_repo():
    return os.path.isdir(os.path.join(PROJECT_DIR, ".git"))


def _git_run(args, capture=False):
    return subprocess.run(
        ["git"] + args,
        cwd=PROJECT_DIR,
        capture_output=capture,
        text=True,
        check=False,
    )


def _git_has_changes():
    r = _git_run(["status", "--porcelain"], capture=True)
    return bool(r.stdout.strip())


def _git_autocommit(prev_version_str):
    if not _git_has_changes():
        return False
    add = _git_run(["add", "-A"])
    if add.returncode != 0:
        print(f"[version_bump] git add failed (rc={add.returncode}); skip commit")
        return False
    msg = f"build snapshot v{prev_version_str}"
    cm = _git_run(["commit", "-m", msg], capture=True)
    if cm.returncode != 0:
        print(f"[version_bump] git commit skipped: {cm.stdout.strip() or cm.stderr.strip()}")
        return False
    return True


def main():
    major, minor = _read_version()
    prev_build = _read_build()

    # A release that covers more than one chip builds more than once, and the
    # counter advancing every time made the two builds carry different firmware
    # numbers -- which is how one release came to ship 0.1.42 for the C6 and
    # 0.1.40 for the C5.  The counter stays monotonic per release, not per
    # invocation: hold it for the second and further chips of the same one.
    #
    #   scripts/build.sh                     # first chip, counter advances
    #   THBR_NO_BUMP=1 scripts/build.sh c5   # same release, same number
    #
    # The header is regenerated either way, so the build still gets a version.h
    # that matches what it will be bundled as.
    hold = os.environ.get("THBR_NO_BUMP") == "1"
    new_build  = prev_build if hold else prev_build + 1
    prev_version = f"{major}.{minor}.{prev_build}"
    new_version  = f"{major}.{minor}.{new_build}"

    if _is_git_repo():
        if _git_autocommit(prev_version):
            print(f"[version_bump] git snapshot committed @ v{prev_version}")
    else:
        print("[version_bump] not a git repo — skipping snapshot")

    if hold:
        print(f"[version_bump] THBR_NO_BUMP=1 — holding build number at "
              f"{new_build} for another chip of the same release")
    else:
        _write_build(new_build)

    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = f"""// AUTO-GENERATED by scripts/version_bump.py — do not edit by hand.
// Manual fields are version.txt (MAJOR.MINOR) and build_number.txt.
#ifndef VERSION_H
#define VERSION_H

#define FW_VERSION_MAJOR  {major}
#define FW_VERSION_MINOR  {minor}
#define FW_VERSION_BUILD  {new_build}

#define FW_VERSION_STRING "{new_version}"
#define FW_BUILD_DATE     "{now}"

#endif // VERSION_H
"""
    os.makedirs(os.path.dirname(HEADER_FILE), exist_ok=True)
    _atomic_write(HEADER_FILE, header)

    print(f"[version_bump] FW v{new_version}  built {now}")


main()
